# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dJQRrl56yDIovlr6mywu8L9b_7h_taEO
"""

import streamlit as st
import pandas as pd
import joblib

st.set_page_config(
    page_title="Student Status Prediction",
    page_icon="🎓"
)

@st.cache_resource
def load_artifacts():
    model = joblib.load("random_forest_model.pkl")
    imputer = joblib.load("median_imputer.pkl")
    feature_columns = joblib.load("feature_columns.pkl")

    return model, imputer, feature_columns

model, imputer, feature_columns = load_artifacts()

st.title("🎓 Student Status Prediction")
st.write(
    "Masukkan data mahasiswa untuk mendapatkan prediksi status."
)

st.subheader("Data Mahasiswa")

gender = st.selectbox(
    "Gender",
    ["Male", "Female"]
)

parental_support = st.selectbox(
    "Parental Support",
    ["Low", "Medium", "High"]
)

previous_grade = st.number_input(
    "Previous Grade",
    min_value=0.0,
    max_value=100.0,
    value=75.0
)

extracurricular = st.number_input(
    "Extracurricular Activities",
    min_value=0,
    step=1,
    value=1
)

study_hours = st.number_input(
    "Study Hours",
    min_value=0.0,
    value=5.0
)

attendance = st.number_input(
    "Attendance (%)",
    min_value=0.0,
    max_value=100.0,
    value=80.0
)

online_classes = st.selectbox(
    "Online Classes Taken",
    [False, True]
)

if st.button("Predict"):

    input_df = pd.DataFrame([{
        "Gender": 0 if gender == "Male" else 1,

        "PreviousGrade": previous_grade,

        "ExtracurricularActivities": extracurricular,

        "ParentalSupport": {
            "Low": 0,
            "Medium": 1,
            "High": 2
        }[parental_support],

        "Study Hours": study_hours,

        "Attendance (%)": attendance,

        "Online Classes Taken": int(online_classes)
    }])

    # Pastikan urutan feature sama dengan training
    input_df = input_df.reindex(
        columns=feature_columns
    )

    # Gunakan imputer yang sudah dipelajari
    # dari training data.
    input_imputed = pd.DataFrame(
        imputer.transform(input_df),
        columns=feature_columns
    )

    prediction = model.predict(
        input_imputed
    )[0]

    st.subheader("Hasil Prediksi")

    if prediction == 1:
        st.success("Status diprediksi: 1")
    else:
        st.info("Status diprediksi: 0")